import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { AgentMessage } from "@earendil-works/pi-agent-core";
import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";

import { AUTORESEARCH_COMPACTION_INSTRUCTIONS } from "./autoresearch/constants.ts";
import {
  parseAutoresearchFleetCount,
  registerAutoresearchSupervisor,
  type FleetCommandHandler,
  type SupervisorOptions,
} from "./autoresearch/supervisor.ts";
import { registerWorkerAutoresearch, type WorkerRegistrationOptions } from "./autoresearch/worker.ts";

export const AUTORESEARCH_STATE_TYPE = "autoresearch-state";
export const AUTORESEARCH_STATUS_ID = "autoresearch";
export const COMPACT_TOOL_LOOP_PAUSED_EVENT = "compact-tool-loop:paused";
export const AUTORESEARCH_CONTINUATION_PROMPT =
  "[autoresearch continuation - generated by /autoresearch]\n@program.md";
export const AUTORESEARCH_PROGRAM_DESIGN_SKILL_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "autoresearch",
  "skills",
  "autoresearch-program-design",
  "SKILL.md",
);
export { AUTORESEARCH_COMPACTION_INSTRUCTIONS };

type RunOwner = "operator" | "autoresearch";
type Phase = "off" | "armed" | "running" | "scheduled" | "compacting" | "paused";

interface PersistedState {
  version: 2;
  enabled: boolean;
  startedAt: number | null;
  turns: number;
}

interface RestoredState {
  enabled: boolean;
  malformed: boolean;
  startedAt?: number;
  turns: number;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function restoreState(ctx: ExtensionContext, now: () => number): RestoredState {
  const entries = ctx.sessionManager.getBranch();
  for (let index = entries.length - 1; index >= 0; index -= 1) {
    const entry = entries[index];
    if (entry.type !== "custom" || entry.customType !== AUTORESEARCH_STATE_TYPE) continue;

    if (!isRecord(entry.data) || typeof entry.data.enabled !== "boolean") {
      return { enabled: false, malformed: true, turns: 0 };
    }

    if (entry.data.version === 1) {
      return {
        enabled: entry.data.enabled,
        malformed: false,
        startedAt: entry.data.enabled ? now() : undefined,
        turns: 0,
      };
    }

    const validStartedAt =
      entry.data.startedAt === null ||
      (typeof entry.data.startedAt === "number" && Number.isFinite(entry.data.startedAt));
    const validTurns =
      typeof entry.data.turns === "number" &&
      Number.isInteger(entry.data.turns) &&
      entry.data.turns >= 0;
    if (
      entry.data.version !== 2 ||
      !validStartedAt ||
      !validTurns ||
      (entry.data.enabled && entry.data.startedAt === null)
    ) {
      return { enabled: false, malformed: true, turns: 0 };
    }

    return {
      enabled: entry.data.enabled,
      malformed: false,
      startedAt: entry.data.startedAt ?? undefined,
      turns: entry.data.turns,
    };
  }

  return { enabled: false, malformed: false, turns: 0 };
}

function messageText(message: AgentMessage): string {
  if (message.role !== "user") return "";
  if (typeof message.content === "string") return message.content;
  return message.content
    .filter((item): item is { type: "text"; text: string } => item.type === "text")
    .map((item) => item.text)
    .join("\n");
}

function hasObjective(ctx: ExtensionContext): boolean {
  return ctx.sessionManager.getBranch().some((entry) => {
    if (entry.type !== "message" || entry.message.role !== "user") return false;
    const text = messageText(entry.message).trim();
    return text.length > 0;
  });
}

function finalAssistantStopReason(messages: AgentMessage[]): string | undefined {
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    const message = messages[index];
    if (message.role === "assistant") return message.stopReason;
  }
  return undefined;
}

function formatDuration(durationMs: number): string {
  const totalSeconds = Math.max(0, Math.floor(durationMs / 1_000));
  if (totalSeconds < 60) return `${totalSeconds}s`;
  const totalMinutes = Math.floor(totalSeconds / 60);
  if (totalMinutes < 60) return `${totalMinutes}m ${totalSeconds % 60}s`;
  return `${Math.floor(totalMinutes / 60)}h ${totalMinutes % 60}m`;
}

const PHASE_LABELS: Record<Phase, string> = {
  off: "off",
  armed: "ready",
  running: "running",
  scheduled: "continuing",
  compacting: "checkpointing",
  paused: "paused",
};

export interface AutoresearchOptions {
  startTimeoutMs?: number;
  compactionTimeoutMs?: number;
  statusIntervalMs?: number;
  loadProgram?: (ctx: ExtensionContext) => string;
  now?: () => number;
  supervisor?: SupervisorOptions;
  worker?: WorkerRegistrationOptions;
}

interface LegacyAutoresearchOptions extends AutoresearchOptions {
  fleetCommandHandler?: FleetCommandHandler;
}

export function registerLegacyAutoresearch(
  pi: ExtensionAPI,
  {
    startTimeoutMs = 30_000,
    compactionTimeoutMs = 180_000,
    statusIntervalMs = 5_000,
    loadProgram = (ctx) => readFileSync(resolve(ctx.cwd, "program.md"), "utf8"),
    now = Date.now,
    fleetCommandHandler,
  }: LegacyAutoresearchOptions = {},
) {
  let enabled = false;
  let phase: Phase = "off";
  let pausedReason: string | undefined;
  let startedAt: number | undefined;
  let turns = 0;
  let inputEpoch = 0;
  let agentEndInputEpoch = 0;
  let runtimeGeneration = 0;
  let scheduled: ReturnType<typeof setTimeout> | undefined;
  let startWatchdog: ReturnType<typeof setTimeout> | undefined;
  let compactionWatchdog: ReturnType<typeof setTimeout> | undefined;
  let statusTimer: ReturnType<typeof setInterval> | undefined;
  let compactionInFlight = false;
  let compactionToken = 0;
  let pendingRunOwner: RunOwner | undefined;
  let activeRunOwner: RunOwner | undefined;
  let activeRunGeneration: number | undefined;
  let agentEndRunGeneration: number | undefined;
  let finalStopReason: string | undefined;
  let currentCtx: ExtensionContext | undefined;
  let compactionPaused = false;

  const clearScheduled = () => {
    if (scheduled !== undefined) clearTimeout(scheduled);
    scheduled = undefined;
  };

  const clearStartWatchdog = () => {
    if (startWatchdog !== undefined) clearTimeout(startWatchdog);
    startWatchdog = undefined;
  };

  const clearCompactionWatchdog = () => {
    if (compactionWatchdog !== undefined) clearTimeout(compactionWatchdog);
    compactionWatchdog = undefined;
  };

  const cancelCompaction = () => {
    compactionToken += 1;
    compactionInFlight = false;
    clearCompactionWatchdog();
  };

  const clearStatusTimer = () => {
    if (statusTimer !== undefined) clearInterval(statusTimer);
    statusTimer = undefined;
  };

  const updateStatus = (ctx: ExtensionContext) => {
    if (!enabled) {
      clearStatusTimer();
      ctx.ui.setStatus(AUTORESEARCH_STATUS_ID, undefined);
      return;
    }

    if (ctx.mode === "tui" && statusIntervalMs > 0 && statusTimer === undefined) {
      statusTimer = setInterval(() => updateStatus(ctx), statusIntervalMs);
    }

    const theme = ctx.ui.theme;
    const stateColor = phase === "paused" ? "warning" : phase === "running" ? "success" : "muted";
    const command = theme.fg("accent", "/autoresearch");
    const state = theme.fg(stateColor, PHASE_LABELS[phase]);
    const turnLabel = `${turns} ${turns === 1 ? "turn" : "turns"}`;
    const duration = formatDuration(now() - (startedAt ?? now()));
    const separator = theme.fg("dim", " · ");
    const details = theme.fg("dim", `${turnLabel} · ${duration}`);
    ctx.ui.setStatus(
      AUTORESEARCH_STATUS_ID,
      `${command}${separator}${state}${separator}${details}`,
    );
  };

  const setPhase = (ctx: ExtensionContext, next: Phase, reason?: string) => {
    phase = next;
    pausedReason = reason;
    updateStatus(ctx);
  };

  const pause = (ctx: ExtensionContext, reason: string, notify = true) => {
    runtimeGeneration += 1;
    clearScheduled();
    clearStartWatchdog();
    cancelCompaction();
    setPhase(ctx, "paused", reason);
    if (notify && ctx.hasUI) {
      ctx.ui.notify(`Autoresearch paused: ${reason}. Use /autoresearch on to resume.`, "warning");
    }
  };

  const persist = (nextEnabled: boolean, force = false) => {
    if (enabled === nextEnabled && !force) return;
    if (nextEnabled && !enabled) {
      startedAt = now();
      turns = 0;
    } else if (!nextEnabled) {
      startedAt = undefined;
      turns = 0;
    }
    enabled = nextEnabled;
    const state: PersistedState = {
      version: 2,
      enabled,
      startedAt: startedAt ?? null,
      turns,
    };
    pi.appendEntry(AUTORESEARCH_STATE_TYPE, state);
  };

  const isBenignCompactionError = (error: Error) =>
    error.message === "Nothing to compact (session too small)" || error.message === "Already compacted";

  const submitContinuation = (
    ctx: ExtensionContext,
    generation: number,
    epoch: number,
  ) => {
    if (generation !== runtimeGeneration || !enabled) return;
    if (epoch !== inputEpoch || !ctx.isIdle() || ctx.hasPendingMessages()) {
      setPhase(ctx, "armed");
      return;
    }

    try {
      pendingRunOwner = "autoresearch";
      clearStartWatchdog();
      startWatchdog = setTimeout(() => {
        startWatchdog = undefined;
        if (
          generation === runtimeGeneration &&
          enabled &&
          pendingRunOwner === "autoresearch" &&
          ctx.isIdle()
        ) {
          pendingRunOwner = undefined;
          pause(ctx, "continuation was submitted but did not start");
        }
      }, startTimeoutMs);
      const program = loadProgram(ctx).trim();
      if (!program) throw new Error("program.md is empty");
      pi.sendUserMessage(`${AUTORESEARCH_CONTINUATION_PROMPT}\n\n${program}`);
      setPhase(ctx, "running");
    } catch (error) {
      clearStartWatchdog();
      pendingRunOwner = undefined;
      pause(ctx, `continuation failed: ${error instanceof Error ? error.message : String(error)}`);
    }
  };

  const compactThenContinue = (
    ctx: ExtensionContext,
    generation: number,
    epoch: number,
  ) => {
    let completed = false;
    const token = ++compactionToken;
    compactionInFlight = true;
    const finish = (error?: Error, compacted = false) => {
      if (completed || token !== compactionToken) return;
      completed = true;
      compactionInFlight = false;
      clearCompactionWatchdog();
      if (generation !== runtimeGeneration || !enabled) return;
      if (error && !isBenignCompactionError(error)) {
        pause(ctx, `compaction failed: ${error.message}`);
        return;
      }
      if (compacted) persist(true, true);
      submitContinuation(ctx, generation, epoch);
    };

    setPhase(ctx, "compacting");
    compactionWatchdog = setTimeout(
      () => finish(new Error("compaction did not complete in time")),
      compactionTimeoutMs,
    );
    try {
      ctx.compact({
        customInstructions: AUTORESEARCH_COMPACTION_INSTRUCTIONS,
        onComplete: () => finish(undefined, true),
        onError: (error) => finish(error),
      });
    } catch (error) {
      finish(error instanceof Error ? error : new Error(String(error)));
    }
  };

  const scheduleContinuation = (ctx: ExtensionContext) => {
    if (!enabled || scheduled !== undefined || compactionInFlight) return;

    const generation = runtimeGeneration;
    const epoch = inputEpoch;
    setPhase(ctx, "scheduled");

    scheduled = setTimeout(() => {
      scheduled = undefined;
      if (generation !== runtimeGeneration || !enabled) return;
      if (epoch !== inputEpoch || !ctx.isIdle() || ctx.hasPendingMessages()) {
        setPhase(ctx, "armed");
        return;
      }
      compactThenContinue(ctx, generation, epoch);
    }, 0);
  };

  const restore = (ctx: ExtensionContext) => {
    runtimeGeneration += 1;
    clearScheduled();
    clearStartWatchdog();
    cancelCompaction();
    clearStatusTimer();
    currentCtx = ctx;
    pendingRunOwner = undefined;
    activeRunOwner = undefined;
    activeRunGeneration = undefined;
    agentEndRunGeneration = undefined;
    finalStopReason = undefined;
    compactionPaused = false;

    const restored = restoreState(ctx, now);
    enabled = restored.enabled;
    startedAt = restored.startedAt;
    turns = restored.turns;
    if (restored.malformed) {
      phase = "off";
      pausedReason = undefined;
      startedAt = undefined;
      turns = 0;
      updateStatus(ctx);
      if (ctx.hasUI) {
        ctx.ui.notify("Ignored malformed autoresearch session state and failed closed to off.", "warning");
      }
      return;
    }

    phase = enabled ? "armed" : "off";
    pausedReason = undefined;
    updateStatus(ctx);
  };

  pi.registerCommand("autoresearch", {
    description: "Start a multi-worker supervisor with a count, or toggle legacy continuation with on, off, or status",
    handler: async (args, ctx) => {
      const requestedAction = args.trim().toLowerCase();
      const fleetCount = parseAutoresearchFleetCount(requestedAction);
      if (fleetCount !== undefined) {
        if (!fleetCommandHandler) {
          if (ctx.hasUI) ctx.ui.notify("Multi-worker autoresearch requires the full Pi extension API.", "error");
          return;
        }
        fleetCommandHandler.start(fleetCount, ctx);
        return;
      }
      if (!requestedAction && fleetCommandHandler && await fleetCommandHandler.stop(ctx)) {
        if (enabled) persist(false);
        runtimeGeneration += 1;
        clearScheduled();
        clearStartWatchdog();
        cancelCompaction();
        setPhase(ctx, "off");
        return;
      }
      const action = requestedAction || (enabled ? "off" : "on");

      if (action === "on") {
        persist(true);
        compactionPaused = false;
        if (compactionInFlight) {
          if (ctx.hasUI) ctx.ui.notify("Autoresearch is already compacting this checkpoint.", "info");
          return;
        }
        setPhase(ctx, ctx.isIdle() ? "armed" : "running");
        if (ctx.hasUI) {
          ctx.ui.notify(
            hasObjective(ctx)
              ? "Autoresearch enabled for this session."
              : "Autoresearch enabled. Submit a research program or objective to start.",
            "info",
          );
        }
        if (ctx.isIdle() && hasObjective(ctx)) scheduleContinuation(ctx);
        return;
      }

      if (action === "off") {
        if (fleetCommandHandler && await fleetCommandHandler.stop(ctx)) {
          if (enabled) persist(false);
          runtimeGeneration += 1;
          clearScheduled();
          clearStartWatchdog();
          cancelCompaction();
          setPhase(ctx, "off");
          return;
        }
        const shouldAbort = activeRunOwner === "autoresearch" && !ctx.isIdle();
        persist(false);
        runtimeGeneration += 1;
        clearScheduled();
        clearStartWatchdog();
        cancelCompaction();
        setPhase(ctx, "off");
        if (shouldAbort) ctx.abort();
        if (ctx.hasUI) ctx.ui.notify("Autoresearch disabled for this session.", "info");
        return;
      }

      if (action === "status") {
        if (fleetCommandHandler?.status(ctx)) return;
        const owner = activeRunOwner ? `, ${activeRunOwner} run` : "";
        const reason = pausedReason ? `, reason: ${pausedReason}` : "";
        const queued = scheduled !== undefined ? ", continuation scheduled" : "";
        if (ctx.hasUI) {
          ctx.ui.notify(
            `Autoresearch is ${enabled ? "enabled" : "off"} (${phase}${owner}${reason}${queued}); state is session- and branch-local.`,
            "info",
          );
        }
        return;
      }

      if (ctx.hasUI) ctx.ui.notify("Usage: /autoresearch [1-4|on|off|status]", "warning");
    },
  });

  pi.on("session_start", (_event, ctx) => restore(ctx));
  pi.on("session_tree", (_event, ctx) => restore(ctx));

  pi.on("session_shutdown", (_event, ctx) => {
    runtimeGeneration += 1;
    clearScheduled();
    clearStartWatchdog();
    cancelCompaction();
    clearStatusTimer();
    unsubscribeCompactionPause();
    ctx.ui.setStatus(AUTORESEARCH_STATUS_ID, undefined);
    currentCtx = undefined;
  });

  pi.on("input", (event, ctx) => {
    inputEpoch += 1;
    pendingRunOwner =
      event.source === "extension" && event.text.startsWith(AUTORESEARCH_CONTINUATION_PROMPT)
        ? "autoresearch"
        : "operator";
    if (enabled) setPhase(ctx, "running");
  });

  pi.on("agent_start", (_event, ctx) => {
    clearStartWatchdog();
    activeRunOwner = pendingRunOwner ?? "operator";
    activeRunGeneration = runtimeGeneration;
    agentEndRunGeneration = undefined;
    pendingRunOwner = undefined;
    finalStopReason = undefined;
    compactionPaused = false;

    if (activeRunOwner === "autoresearch" && !enabled) {
      ctx.abort();
      return;
    }

    if (enabled) {
      turns += 1;
      persist(true, true);
      setPhase(ctx, "running");
    }
  });

  pi.on("agent_end", (event) => {
    finalStopReason = finalAssistantStopReason(event.messages);
    agentEndInputEpoch = inputEpoch;
    agentEndRunGeneration = activeRunGeneration;
  });

  pi.on("agent_settled", (_event, ctx) => {
    const settledRunGeneration = agentEndRunGeneration;
    activeRunOwner = undefined;
    activeRunGeneration = undefined;
    agentEndRunGeneration = undefined;
    if (!enabled) return;
    if (settledRunGeneration !== runtimeGeneration) {
      setPhase(ctx, "armed");
      return;
    }

    if (compactionPaused) {
      pause(ctx, "context compaction could not recover", false);
      return;
    }

    if (finalStopReason !== "stop") {
      pause(ctx, finalStopReason ?? "no terminal assistant response", finalStopReason !== "toolUse");
      return;
    }

    if (inputEpoch !== agentEndInputEpoch || ctx.hasPendingMessages()) {
      setPhase(ctx, "armed");
      return;
    }

    scheduleContinuation(ctx);
  });

  const unsubscribeCompactionPause = pi.events.on(COMPACT_TOOL_LOOP_PAUSED_EVENT, () => {
    compactionPaused = true;
    const ctx = currentCtx;
    if (ctx && enabled) pause(ctx, "context compaction could not recover", false);
  });
}

export function registerAutoresearch(pi: ExtensionAPI, options: AutoresearchOptions = {}): void {
  if (process.env.AUTORESEARCH_ROLE === "worker") {
    registerWorkerAutoresearch(pi, options.worker);
    return;
  }
  pi.on("resources_discover", () => ({
    skillPaths: [AUTORESEARCH_PROGRAM_DESIGN_SKILL_PATH],
  }));
  const supportsSupervisor =
    typeof pi.registerTool === "function" &&
    typeof pi.getActiveTools === "function" &&
    typeof pi.setActiveTools === "function" &&
    typeof pi.getThinkingLevel === "function";
  const supervisor = supportsSupervisor ? registerAutoresearchSupervisor(pi, options.supervisor) : undefined;
  registerLegacyAutoresearch(pi, { ...options, fleetCommandHandler: supervisor });
}

export default registerAutoresearch;
